- name: "Copy app to server"
  ansible.builtin.copy:
    src: files/app/
    dest: /app/
    directory_mode:
    mode: "0755"

- name: "Ensure NodeJS in $PATH"
  ansible.builtin.shell: >
    source ~/.bashrc
  args:
    executable: /bin/bash
  register: out
  changed_when: out.rc != 0
  become: true
  become_user: ansible

- name: "Install app packages"
  community.general.npm:
    path: /app
  become: true
  become_user: ansible
