- name: "Copy app to server"
  ansible.builtin.copy:
    src: files/app/
    dest: /app/
    directory_mode:
    owner: ansible
    group: ansible
    mode: "0755"

- name: "Install app packages"
  ansible.builtin.shell: >
    $(which npm) install
  args:
    chdir: /app
  register: out
  changed_when: out.rc != 0
  become: true
  become_user: ansible
