- name: "Copy app to server"
  ansible.builtin.copy:
    src: files/app/
    dest: /var/www/app/
    directory_mode:
    owner: ansible
    group: ansible
    mode: "0644"

- name: "Install app packages"
  community.general.npm:
    path: /var/www/app
    state: present
  become: true
  become_user: ansible
