- name: "Copy app to server"
  become: true
  ansible.builtin.copy:
    src: files/app/
    dest: /var/www/app/
    directory_mode:
    owner: www-data
    group: www-data
    mode: "0644"

- name: "Install app packages"
  become: true
  community.general.npm:
    path: /var/www/app/
