- name: "Copy app to server"
  ansible.builtin.copy:
    src: files/app/
    dest: /app/
    directory_mode:
    owner: ansible
    group: ansible
    mode: "0755"

- name: "Ensure node && npm in $PATH"
  ansible.builtin.shell: >
    source /home/ansible/.bashrc
  args:
    executable: /bin/bash
  register: out
  changed_when: out.rc != 0
  become: true
  become_user: ansible

- name: "Install app packages"
  ansible.builtin.shell: >
    npm install
  args:
    chdir: /app
    executable: /bin/bash
  register: out
  changed_when: out.rc != 0
  become: true
  become_user: ansible
