- name: "Copy app to server"
  ansible.builtin.copy:
    src: files/app/
    dest: /app/
    directory_mode:
    owner: ansible
    group: ansible
    mode: "0755"

- name: "Install app packages"
  ansible.builtin.shell: >
    cd /app && \
    /home/ansible/.nvm/versions/node/v10.13.0/bin/npm install
  register: out
  changed_when: out.rc != 0
  become: true
  become_user: ansible
