- name: "Install nginx"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - nginx

- name: "Copy app to www-data directory"
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /app/dist/front/
    dest: /var/www/app/
    owner: www-data
    group: www-data
    mode: "0755"

- name: "Update nginx configuration for angular"
  become: true
  ansible.builtin.copy:
    src: files/app.nginx
    dest: /etc/nginx/sites-available/app
    owner: www-data
    group: www-data
    mode: "0755"

- name: "Symlink from sites-available to sites-enabled"
  ansible.builtin.file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    owner: www-data
    group: www-data
    mode: "0755"
    state: link

- name: "Validate nginx configuration"
  become: true
  ansible.builtin.command:
    cmd: "nginx -t"
  register: out
  changed_when: out.rc != 0

- name: "Add ansible user to www-data group"
  become: true
  ansible.builtin.user:
    name: ansible
    group: www-data
    state: present

- name: "Restart nginx with configuration updates"
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
