---
- name: "Load NodeJS variables"
  ansible.builtin.include_vars: nodejs.vars.ansible.yml

- name: "Install package dependencies"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - ca-certificates
      - apt-transport-https
      - git

- name: "Install NVM"
  become: false
  become_user: ansible
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "/home/ansible/.nvm/nvm.sh"

- name: "Install NodeJS"
  become: false
  become_user: ansible
  ansible.builtin.shell: >
    source /home/ansible/.nvm/nvm.sh && nvm install {{ nodejs_version }}
  args:
    executable: /bin/bash
  register: out
  changed_when: out.rc != 0

- name: "Obtain app from remote repository"
  become: true
  ansible.builtin.git:
    repo: "http://{{ nodejs_app_git_host }}:{{ nodejs_app_git_port }}/nsa-700/angular-app.git"
    dest: /app
    version: develop
    force: true

- name: "Set permissions on application"
  become: true
  ansible.builtin.file:
    path: /var/www/app
    recurse: true
    owner: ansible
    group: ansible
    mode: "0644"

- name: "Install app packages"
  become: false
  become_user: ansible
  ansible.builtin.command:
    cmd: >
      bash -c "source /home/ansible/.nvm/nvm.sh &&
      nvm exec {{ nodejs_version }} npm install"
    chdir: /app
  register: out
  changed_when: out.rc != 0

- name: "Build app"
  become: false
  become_user: ansible
  ansible.builtin.command:
    cmd: >
      bash -c "source /home/ansible/.nvm/nvm.sh &&
      nvm exec {{ nodejs_version }} npm run build"
    chdir: /app
  register: out
  changed_when: out.rc != 0
