---
- name: "Load NodeJS variables"
  ansible.builtin.include_vars: nodejs.vars.ansible.yml

- name: "Install package dependencies"
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - ca-certificates
      - apt-transport-https

- name: "Install NVM"
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "/home/ansible/.nvm/nvm.sh"
  become: false
  become_user: ansible

- name: "Install NodeJS"
  ansible.builtin.shell: >
    source /home/ansible/.nvm/nvm.sh && nvm install 10.13.0 && nvm use 10.13.0
  args:
    executable: /bin/bash
  register: out
  changed_when: out.rc != 0
  become: false
  become_user: ansible

- name: "Copy app to server"
  ansible.builtin.copy:
    src: files/app/
    dest: /app/
    directory_mode:
    owner: ansible
    group: ansible
    mode: "0755"

- name: "Install app packages"
  community.general.npm:
    path: /app
    state: present
  become: false
  become_user: ansible
