---
- name: "Load NodeJS variables"
  ansible.builtin.include_vars: nodejs.vars.ansible.yml

- name: "Install package dependencies"
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - ca-certificates
      - apt-transport-https

- name: "Install NVM"
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "/home/ansible/.nvm/nvm.sh"

- name: "Install NodeJS"
  ansible.builtin.command:
    cmd: "nvm install {{ nodejs_version }}"
  register: out
  changed_when: out.rc != 0
